# Generated by Django 5.2.3 on 2025-06-30 10:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Service Group Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investment Service Group',
                'verbose_name_plural': 'Investment Service Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Invested Amount (AED)')),
                ('tokens_generated', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated based on invested amount (e.g., 1 token per 100 AED).', max_digits=15, null=True, verbose_name='Tokens Generated')),
                ('investment_period', models.PositiveIntegerField(choices=[(3, '3 Years'), (5, '5 Years'), (10, '10 Years')], verbose_name='Investment Period')),
                ('interest_rate_applied', models.DecimalField(blank=True, decimal_places=2, help_text='The interest rate applied at the time of investment.', max_digits=5, null=True, verbose_name='Interest Rate Applied (%)')),
                ('final_return_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated based on invested amount and interest rate (Principal + Profit).', max_digits=15, null=True, verbose_name='Final Return Amount (AED)')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, help_text='The calculated profit from the investment (Final Return - Invested Amount).', max_digits=15, null=True, verbose_name='Profit (AED)')),
                ('total_portfolio_value', models.DecimalField(blank=True, decimal_places=2, help_text='Sum of invested amount and profit.', max_digits=15, null=True, verbose_name='Total Portfolio Value (AED)')),
                ('investment_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Investment Start Date')),
                ('investment_end_date', models.DateField(blank=True, help_text='Calculated based on start date and period.', null=True, verbose_name='Investment End Date')),
                ('is_investment_active', models.BooleanField(default=True, verbose_name='Is Investment Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_service_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments_in_group', to='investors.investmentservicegroup', verbose_name='Selected Service Group for Investment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['user__name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestRateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_in_years', models.PositiveIntegerField(verbose_name='Investment Period (Years)')),
                ('interest_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Percentage (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_settings', to='investors.investmentservicegroup', verbose_name='Associated Service Group')),
            ],
            options={
                'verbose_name': 'Interest Rate Setting',
                'verbose_name_plural': 'Interest Rate Settings',
                'ordering': ['service_group__name', 'period_in_years'],
                'unique_together': {('service_group', 'period_in_years')},
            },
        ),
    ]
