# Generated by Django 5.2.3 on 2025-07-11 06:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('share_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestRateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_in_years', models.PositiveIntegerField(choices=[(3, '3 Years'), (5, '5 Years'), (10, '10 Years')])),
                ('interest_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_rates', to='investors.investmentservicegroup')),
            ],
            options={
                'ordering': ['service_group__name', 'period_in_years'],
                'unique_together': {('service_group', 'period_in_years')},
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_shares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The total number of shares purchased for this investment.', max_digits=15, verbose_name='Number of Shares')),
                ('invested_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Invested Amount (AED)')),
                ('investment_period', models.PositiveIntegerField(choices=[(3, '3 Years'), (5, '5 Years'), (10, '10 Years')], verbose_name='Investment Period')),
                ('interest_rate_applied', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='The interest rate applied at the time of investment.', max_digits=7, verbose_name='Interest Rate Applied (%)')),
                ('final_return_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated based on invested amount and interest rate (Principal + Profit).', max_digits=15, verbose_name='Final Return Amount (AED)')),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The calculated *projected* profit from the investment at full maturity (Final Return - Invested Amount).', max_digits=15, verbose_name='Profit (AED)')),
                ('total_portfolio_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current value of the portfolio (Invested Amount + Current Accrued Profit).', max_digits=15, verbose_name='Total Portfolio Value (AED)')),
                ('current_accrued_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit earned from the investment up to the current date.', max_digits=15, verbose_name='Current Accrued Profit (AED)')),
                ('investment_start_date', models.DateField(auto_now_add=True, verbose_name='Investment Start Date')),
                ('investment_end_date', models.DateField(blank=True, help_text='Calculated based on start date and period.', null=True, verbose_name='Investment End Date')),
                ('is_investment_active', models.BooleanField(default=True, verbose_name='Is Investment Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_service_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments_in_group', to='investors.investmentservicegroup', verbose_name='Selected Service Group for Investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['user__id', 'created_at'],
                'unique_together': {('user', 'selected_service_group', 'investment_period')},
            },
        ),
    ]
