# Generated by Django 5.2.3 on 2025-07-03 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='investment_start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Investment Start Date'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='Associated User'),
        ),
        migrations.AlterUniqueTogether(
            name='investor',
            unique_together={('user', 'selected_service_group', 'investment_period')},
        ),
    ]
