# Generated by Django 5.2.3 on 2025-07-09 09:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_alter_investor_investment_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={'ordering': ['user__mobile_number', 'created_at'], 'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
        migrations.RemoveField(
            model_name='investor',
            name='tokens_generated',
        ),
        migrations.AddField(
            model_name='investmentservicegroup',
            name='share_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='The value of one share in this service group (e.g., 100.00 AED).', max_digits=10, verbose_name='Share Value (AED per share)'),
        ),
        migrations.AddField(
            model_name='investor',
            name='number_of_shares',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The total number of shares purchased for this investment.', max_digits=15, verbose_name='Number of Shares'),
        ),
    ]
