# Generated by Django 5.2.3 on 2025-06-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sha', '0003_user_account_number_user_bank_name_user_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number for OTP authentication and primary login identifier (username).', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text="User's display name.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[('service', 'Service'), ('business', 'Business'), ('private_sector', 'Private Sector'), ('govt_central_state', 'Central/State Government'), ('pensioner', 'Pensioner'), ('senior_citizen', 'Senior Citizen'), ('minor', 'Minor'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
