# Generated by Django 5.2.3 on 2025-06-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sha', '0004_alter_user_mobile_number_alter_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editable_fields', models.JSONField(blank=True, default=list, help_text='A JSON list of profile field names that users can update. Example: ["bio", "website"]')),
            ],
            options={
                'verbose_name_plural': 'User Profile Settings',
            },
        ),
    ]
