# Generated by Django 5.2.3 on 2025-07-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sha', '0005_userprofilesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ifsc',
        ),
        migrations.AddField(
            model_name='user',
            name='bank_details',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
